import{a as b,S as w,i}from"./assets/vendor-C4-ZuMk8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const L="46118287-c5ba04b36aad3afec959570e4",v="https://pixabay.com/api/";async function y(s){const t=`${v}?key=${L}&q=${encodeURIComponent(s)}&image_type=photo&orientation=horizontal&safesearch=true`;try{const r=await b.get(t);return{images:r.data.hits,totalHits:r.data.totalHits}}catch{throw new Error("Network response was not ok")}}const E=new w(".gallery a");function S(){const s=document.querySelector(".gallery");s.innerHTML=""}function f(s){const t=document.querySelector(".gallery"),r=s.map(({webformatURL:a,largeImageURL:e,tags:o,likes:n,views:g,comments:h,downloads:p})=>`
            <a href="${e}" class="gallery-link">
                <div class="photo-card">
                    <img src="${a}" alt="${o}" loading="lazy" />
                    <div class="info">
                        <p class="info-item"><b>Likes</b> ${n}</p>
                        <p class="info-item"><b>Views</b> ${g}</p>
                        <p class="info-item"><b>Comments</b> ${h}</p>
                        <p class="info-item"><b>Downloads</b> ${p}</p>
                    </div>
                </div>
            </a>
        `).join("");t.insertAdjacentHTML("beforeend",r),E.refresh()}const q=document.querySelector("#search-form"),c=document.querySelector(".loader"),d=document.querySelector("#load-more"),m=document.querySelector(".gallery");let $="",u=0,l=0;const P=15,H=Math.ceil(u/P);d.style.display="none";q.addEventListener("submit",async s=>{s.preventDefault();const t=s.target.elements.searchQuery.value.trim();if(!t){i.error({title:"Error",message:"Please enter a search query."});return}c.classList.remove("hidden"),S(),l=0;try{const{images:r,totalHits:a}=await y(t);u=a,l+=r.length,r.length===0?i.warning({title:"No Results",message:"Sorry, no images match your search query."}):(f(r),d.style.display=l>=u?"none":"block")}catch(r){i.error({title:"Error",message:"Something went wrong. Please try again later."}),console.error("Error fetching images:",r)}finally{c.classList.add("hidden")}});d.addEventListener("click",async()=>{c.classList.remove("hidden");try{const{images:t}=await y($);l+=t.length,t.length>0&&f(t),l>H&&(d.style.display="none",i.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."}))}catch{i.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{c.classList.add("hidden")}const s=m.firstElementChild?m.firstElementChild.getBoundingClientRect().height:0;window.scrollBy({top:s*2,behavior:"smooth"})});
//# sourceMappingURL=index.js.map
